name: Deploy main.py to VM

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Debug SSH connection
      run: |
        ssh -vvv superuser@217.115.115.156