name: Deploy main.py to VM
#test
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa 217.115.115.156 >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Copy main.py to VM Home Directory
      run: |
        scp main.py superuser@217.115.115.156:/home/superuser/

    - name: Move main.py to ie_checker Directory
      run: |
        ssh superuser@217.115.115.156 'mv /home/superuser/main.py /home/superuser/ie_checker/'


        